name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/*"
      - "**/eslint*"
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.css"
      - "**/*.html"
      - "**/*.json"

permissions:
  contents: read
  pull-requests: write
  deployments: write

jobs:
  test-and-lint:
    name: Test and Lint
    uses: ./.github/workflows/test-and-lint.yml

  deploy-web-preview:
    name: Web
    needs:
      - test-and-lint
    runs-on: ubuntu-latest
    outputs:
      deployed: ${{ steps.check-web-code.outputs.changed }}
      web_url: ${{ steps.deploy-web-preview.outputs.deploy-url || 'https://ecookbook.netlify.app' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Check for Web App changes
        id: check-web-code
        run: |
          echo "Checking for Web App changes..."
          git fetch origin main
          if git diff --name-only origin/main...HEAD | grep -E '^packages/(shared|web)/' | grep -v '.*\.test\.tsx?'; then
            echo "Web App changes detected."
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No Web App changes detected."
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Build the app
        if: steps.check-web-code.outputs.changed == 'true'
        run: npm ci --workspace=packages/web && npm run build --workspace=packages/web
      - name: Deploy to Netlify
        if: steps.check-web-code.outputs.changed == 'true'
        id: deploy-web-preview
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: "./packages/web/dist"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: ${{ github.event.pull_request.title }}
          enable-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_TOKEN_DEPLOY_PROD }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PROJECT_ID_PROD }}
        timeout-minutes: 1
